name: Deploy to VPS

on:
    push:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy using ssh
              uses: https://github.com/appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  port: ${{ secrets.PORT }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  script: |
                      cd services/SOK-client/
                      git pull origin master
                      docker build . -t sok-client:latest --build-arg VITE_APP_API_URL="${{ secrets.API_URL }}"
                      cd ../
                      docker compose up -d sok-client
